#include "stdint.h"

//u0_sys_iomux
void set_sys_iomux_func(uint32_t func);
void set_sys_iomux_cfg(uint32_t gpio_num, uint32_t func);
void set_pad_gpio6_func(uint32_t func);
int get_pad_gpio6_func(void);
void set_pad_gpio7_func(uint32_t func);
int get_pad_gpio7_func(void);
void set_pad_gpio8_func(uint32_t func);
int get_pad_gpio8_func(void);
void set_pad_gpio9_func(uint32_t func);
int get_pad_gpio9_func(void);
void set_pad_gpio10_func(uint32_t func);
int get_pad_gpio10_func(void);
void set_pad_gpio11_func(uint32_t func);
int get_pad_gpio11_func(void);
void set_pad_gpio12_func(uint32_t func);
int get_pad_gpio12_func(void);
void set_pad_gpio13_func(uint32_t func);
int get_pad_gpio13_func(void);
void set_pad_gpio14_func(uint32_t func);
int get_pad_gpio14_func(void);
void set_pad_gpio15_func(uint32_t func);
int get_pad_gpio15_func(void);
void set_pad_gpio16_func(uint32_t func);
int get_pad_gpio16_func(void);
void set_pad_gpio17_func(uint32_t func);
int get_pad_gpio17_func(void);
void set_pad_gpio18_func(uint32_t func);
int get_pad_gpio18_func(void);
void set_pad_gpio19_func(uint32_t func);
int get_pad_gpio19_func(void);
void set_pad_gpio20_func(uint32_t func);
int get_pad_gpio20_func(void);
void set_pad_gpio21_func(uint32_t func);
int get_pad_gpio21_func(void);
void set_pad_gpio22_func(uint32_t func);
int get_pad_gpio22_func(void);
void set_pad_gpio23_func(uint32_t func);
int get_pad_gpio23_func(void);
void set_pad_gpio24_func(uint32_t func);
int get_pad_gpio24_func(void);
void set_pad_gpio25_func(uint32_t func);
int get_pad_gpio25_func(void);
void set_pad_gpio26_func(uint32_t func);
int get_pad_gpio26_func(void);
void set_pad_gpio27_func(uint32_t func);
int get_pad_gpio27_func(void);
void set_pad_gpio28_func(uint32_t func);
int get_pad_gpio28_func(void);
void set_pad_gpio29_func(uint32_t func);
int get_pad_gpio29_func(void);
void set_pad_gpio30_func(uint32_t func);
int get_pad_gpio30_func(void);
void set_pad_gpio31_func(uint32_t func);
int get_pad_gpio31_func(void);
void set_pad_gpio32_func(uint32_t func);
int get_pad_gpio32_func(void);
void set_pad_gpio33_func(uint32_t func);
int get_pad_gpio33_func(void);
void set_pad_gpio34_func(uint32_t func);
int get_pad_gpio34_func(void);
void set_pad_gpio35_func(uint32_t func);
int get_pad_gpio35_func(void);
void set_pad_gpio36_func(uint32_t func);
int get_pad_gpio36_func(void);
void set_pad_gpio37_func(uint32_t func);
int get_pad_gpio37_func(void);
void set_pad_gpio38_func(uint32_t func);
int get_pad_gpio38_func(void);
void set_pad_gpio39_func(uint32_t func);
int get_pad_gpio39_func(void);
void set_pad_gpio40_func(uint32_t func);
int get_pad_gpio40_func(void);
void set_pad_gpio41_func(uint32_t func);
int get_pad_gpio41_func(void);
void set_pad_gpio42_func(uint32_t func);
int get_pad_gpio42_func(void);
void set_pad_gpio43_func(uint32_t func);
int get_pad_gpio43_func(void);
void set_pad_gpio44_func(uint32_t func);
int get_pad_gpio44_func(void);
void set_pad_gpio45_func(uint32_t func);
int get_pad_gpio45_func(void);
void set_pad_gpio46_func(uint32_t func);
int get_pad_gpio46_func(void);
void set_pad_gpio47_func(uint32_t func);
int get_pad_gpio47_func(void);
void set_pad_gpio48_func(uint32_t func);
int get_pad_gpio48_func(void);
void set_pad_gpio49_func(uint32_t func);
int get_pad_gpio49_func(void);
void set_pad_gpio50_func(uint32_t func);
int get_pad_gpio50_func(void);
void set_pad_gpio51_func(uint32_t func);
int get_pad_gpio51_func(void);
void set_pad_gpio52_func(uint32_t func);
int get_pad_gpio52_func(void);
void set_pad_gpio53_func(uint32_t func);
int get_pad_gpio53_func(void);
void set_pad_gpio54_func(uint32_t func);
int get_pad_gpio54_func(void);
void set_pad_gpio55_func(uint32_t func);
int get_pad_gpio55_func(void);
void set_pad_gpio56_func(uint32_t func);
int get_pad_gpio56_func(void);
void set_pad_gpio57_func(uint32_t func);
int get_pad_gpio57_func(void);
void set_pad_gpio58_func(uint32_t func);
int get_pad_gpio58_func(void);
void set_pad_gpio59_func(uint32_t func);
int get_pad_gpio59_func(void);
void set_pad_gpio60_func(uint32_t func);
int get_pad_gpio60_func(void);
void set_pad_gpio61_func(uint32_t func);
int get_pad_gpio61_func(void);
void set_pad_gpio62_func(uint32_t func);
int get_pad_gpio62_func(void);
void set_pad_gpio63_func(uint32_t func);
int get_pad_gpio63_func(void);

